import type { Metadata } from "next"
import Head from 'next/head'
import {Navigation} from './components/ui/nav/nav'
import { Text } from "./components/ui/text"
import Link from 'next/link'

// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "FarmerVICE",
  description: "This is a capacity building application meant to teach farmers on best practices with regards to livstock farming an d methane reduction techniques.Generated by @JAYR - Joseph Ridge. ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>FarmerVice</title>
      </Head>
      <body
        
      >
        <Navigation>
          <div>
          <Link href="/">
          <Text variant={"subtitle"}> farmerVICE</Text></Link></div>
          
          <div> 
          <Link href="/dashboard">
          <Text variant={"small"}> dashboard</Text>
          </Link>
        
          <Link href="/dashboard">
          <Text variant={"small"}> dashboard</Text>
          </Link>
          
          </div>
        
        </Navigation>
        {children}

      {/* <footer className="bg-white bottom-0 w-screen text-black ">
       @copyright 2025
      </footer> */}
      </body>
    </html>
  );
}
