import type { Metadata } from "next"
import Head from 'next/head'
import { Navigation } from './components/ui/nav/nav'
import { Text } from "./components/ui/text"
import Link from 'next/link'
import "./globals.css";

export const metadata: Metadata = {
  title: "FarmerVICE",
  description: "This is a capacity building application meant to teach farmers on best practices with regards to livstock farming an d methane reduction techniques.Generated by @JAYR - Joseph Ridge. ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>FarmerVice</title>
      </Head>
      <body>
        <Navigation >
          <div>
            <Link href="/">
              <Text variant={"subtitle"}> farmerVICE</Text></Link></div>

          <div>
            <Link href="/login">
              <Text variant={"small"}> login</Text>
            </Link>
          </div>
        </Navigation>
        <div className="w-screen py-10">
          {children}
        </div>

        <footer className="bg-white bottom-0 w-screen text-white bg-black ">
       @copyright 2025
      </footer>
      </body>
    </html>
  );
}
